### ISSUE TITLE
using Jenkins

### ISSUE THREAD

**Issue by ReneCode** [ivx/docker-meetup-workshop#1]
I want to set up a docker container in my jenkins CI build.
- docker-build-step as jenkins plugin installed
- jenkins configure Docker Installations: "Install automatically" + install latest from docker.io

but in the build step jenkins does not install docker, and the docker command fails.
What's my fault ?

btw. I run jenkins in a docker image.

**Comment by tsupertramp** [comment]
You have to allow docker container to access docker socket to start new docker containers via -v /var/run/docker.sock:/var/run/docker.sock

**Comment by ReneCode** [comment]
thank you very much.
--
another question about the workflow in CI / CD in combination with docker:
- jenkins gets the push-hook of the git-repository and
- checkout the sources
- do testing
- build a new docker image
- push this new docker image to docker registry

and now ?  
how would I replace the old running docker container on the remote machine with the new container ? 
something like: 
- docker stop old_container
- docker pull new_image
- docker run new_image ?
will that be done in that one large jenkins build pipeline ?

**Comment by tsupertramp** [comment]
We use a Jenkinsfile in a repository to define the build pipeline.
docker stop/pull/run is abstracted through kuberntes. We use this orchestration tool to run docker containers in production. We need only a rollin update command to exchange the containers.
Here is an example of our Jenkinsfile:
```
def app_name = 'YOUR-APP-NAME'

stage 'Checkout'

node {
  checkout scm
}

stage 'Testing'
node {
  try {
    sh 'docker-compose build --pull'
    sh 'docker-compose run app docker/bin/wait-for-it rabbit:5672 -- docker/bin/run test'
  } catch (err) {
    sh 'docker-compose down -v --remove-orphans'
    throw err
  } finally {
    sh 'docker-compose down -v --remove-orphans'
  }
}

if (env.BRANCH_NAME == 'master') {
  def app

  stage 'Build Image'
  node {
    app = docker.build "invisionag/${app_name}","--pull ."
    app.push("${env.BRANCH_NAME}-${env.BUILD_NUMBER}")
    app.push("latest")
  }

  stage 'Deploy Staging'
  node {
    sh "docker run -v /var/lib/jenkins/credentials/kubectl.config:/root/.kube/config tsupertramp/kubectl-1.2.5 --context staging rolling-update ${app_name} --image=invisionag/${app_name}:${env.BRANCH_NAME}-${env.BUILD_NUMBER} --update-period=1s"
    app.push("staging")
  }

  timeout(time: 8, unit: 'HOURS') {
    stage 'Deploy Production'
    input 'Ready for production?'
    node {
      sh "docker run -v /var/lib/jenkins/credentials/kubectl.config:/root/.kube/config tsupertramp/kubectl-1.2.5 --context prod rolling-update ${app_name} --image=invisionag/${app_name}:${env.BRANCH_NAME}-${env.BUILD_NUMBER} --update-period=1s"
      app.push("production")
    }
  }
}
```
